parameters:
    pw.setting.uri: 'http://www.work.ua/'
    pw.setting.pager_sequence_table: 'pw_sequence'
    pw.setting.profile_link_table: 'pw_profile_page_link'
    pw.setting.profile_table: 'pw_profile'
    pw.setting.pager_root_path: '/ua/resumes-kyiv-it/'
    pw.setting.pager_selector_next: 'ul.pagination li.no-style a'
    pw.setting.profile_link_selector: '.resume-link a'

services:
    pw.scrap.client:
        public: false
        class: 'GuzzleHttp\Client'
        arguments:
            - { base_uri: '%pw.setting.uri%' }

    pw.sequence.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\SequenceContentRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pw.setting.pager_sequence_table%'

    pw.profile.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\D\ProfileRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pw.setting.profile_table%'

    pw.sequence.pager:
        public: false
        class: 'ReenExe\Scrapynizer\Pager\PaginationHunter'
        arguments:
            - '%pw.setting.pager_root_path%'
            - '%pw.setting.pager_selector_next%'

    pw.sequence.link.collection.finder:
        public: false
        class: 'AppBundle\Service\Scrapynizer\LinkCollectionSelectorFinder'
        arguments:
            - '%pw.setting.profile_link_selector%'

    pw.path.process.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\PathProcessRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pw.setting.profile_link_table%'

    pw.link.collection.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\LinkCollectionAnalyzer'
        arguments:
            - '@pw.sequence.link.collection.finder'
            - '@pw.path.process.repository'

    pw.sequence.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\D\SequenceContentAnalyzer'
        arguments:
            - '@pw.link.collection.analyzer'

    pw.sequence.scraper:
        public: false
        class: 'ReenExe\Scrapynizer\Scraper\SequenceScraper'
        arguments:
            - '@pw.scrap.client'
            - '@pw.sequence.repository'
            - '@pw.sequence.pager'
            - '@pw.sequence.analyzer'

    pw.content.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\D\ContentAnalyzer'
        arguments:
            - '@pw.profile.repository'

    pw.target.scrap:
        public: false
        class: 'ReenExe\Scrapynizer\Scraper\CollectionScraper'
        arguments:
            - '@pw.scrap.client'
            - '@pw.path.process.repository'
            - '@pw.content.analyzer'

    pw.sequence.scrap.command.adapter:
        public: false
        class: 'AppBundle\Service\Scrapynizer\QueueCommandAdapter'
        arguments:
            - '@pw.sequence.scraper'

    pw.scrap.target.command.adapter:
        public: false
        class: 'AppBundle\Service\Scrapynizer\QueueCommandAdapter'
        arguments:
            - '@pw.target.scrap'

    pw.sequence.scrap.target.list.command:
        class: 'AppBundle\Command\Core\RunTimeQueueCommand'
        arguments:
            - 'w:sequence:scrap:target:list'
            - '@pw.sequence.scrap.command.adapter'
        tags:
            -  { name: 'console.command' }

    pw.scrap.target.command:
        class: 'AppBundle\Command\Core\RunTimeQueueCommand'
        arguments:
            - 'w:scrap:target'
            - '@pw.scrap.target.command.adapter'
        tags:
            -  { name: 'console.command' }
