services:
  conection_service:
    abstract:  true
    class: AppBundle\Service\ConnectionService
    arguments: ['@doctrine.dbal.default_connection']

  scrap_page_service:
    parent: conection_service
    class: AppBundle\Service\Scrap\PageScraper

  scrap_list_service:
    parent: conection_service
    class: AppBundle\Service\Scrap\ListScraper

  skill.structure_service:
    parent: conection_service
    class: AppBundle\Service\SkillSite\StructureService

  skill.analyze_structure_service:
    parent: conection_service
    class: AppBundle\Service\SkillSite\AnalyzeStructureService