services:
    conection_service:
        abstract:  true
        class: AppBundle\Service\ConnectionService
        arguments:
            - '@doctrine.dbal.default_connection'

    skill.analyze_structure_service:
        parent: conection_service
        class: AppBundle\Service\SkillSite\AnalyzeStructureService

    pd.profile.list.content.storage:
        class: AppBundle\Service\Scrap\ProfileListContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pd_skill_site_list_cache'

    pd.profile.content.storage:
        class: AppBundle\Service\Scrap\ProfileContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pd_skill_site_page_cache'

    pd.list.content.analyzer:
        class: AppBundle\Service\Scrap\ListContentAnalyzer
        arguments:
            - '/developers/'
            - '.next a'
            - '.profile'

    pd.page_path_process:
        class: AppBundle\Service\Scrap\PagePathProcess
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pd_skill_site_page_queue'

    pd.scrap_list_service:
        class:  AppBundle\Service\Scrap\ListScraper
        arguments:
            - '@pd.profile.list.content.storage'
            - '@pd.list.content.analyzer'
            - '@pd.page_path_process'

    pd.scrap_page_service:
        class: AppBundle\Service\Scrap\PageScraper
        arguments:
            - '@pd.profile.content.storage'
            - '@pd.page_path_process'

    pd.skill.structure_service:
        class: AppBundle\Service\SkillSite\StructureService
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@pd.profile.content.storage'

    pw.page_path_process:
        class: AppBundle\Service\Scrap\PagePathProcess
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pw_skill_site_page_queue'

    pw.profile.list.content.storage:
        class: AppBundle\Service\Scrap\ProfileListContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pw_skill_site_list_cache'

    pw.profile.content.storage:
        class: AppBundle\Service\Scrap\ProfileContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'pw_skill_site_page_cache'

    pw.list.content.analyzer:
        class: AppBundle\Service\Scrap\ListContentAnalyzer
        arguments:
            - '/resumes-it/'
            - '.perpageNavigation a'
            - '.tblSearch .ttl a.bf'

    pw.scrap_list_service:
        class:  AppBundle\Service\Scrap\ListScraper
        arguments:
            - '@pw.profile.list.content.storage'
            - '@pw.list.content.analyzer'
            - '@pw.page_path_process'

    pw.scrap_page_service:
        class: AppBundle\Service\Scrap\PageScraper
        arguments:
            - '@pw.profile.content.storage'
            - '@pw.page_path_process'

    d.scrap.skill.site.list:
        class: AppBundle\Command\Core\RunTimeQueueCommand
        arguments:
            - 'd:scrap:skill:site:list'
            - '@pd.scrap_list_service'
        tags:
            -  { name: console.command }

    d.scrap.skill.site.page:
        class: AppBundle\Command\Core\RunTimeQueueCommand
        arguments:
            - 'd:scrap:skill:site:page'
            - '@pd.scrap_page_service'
        tags:
            -  { name: console.command }

    w.scrap.skill.site.list:
        class: AppBundle\Command\Core\RunTimeQueueCommand
        arguments:
            - 'w:scrap:skill:site:list'
            - '@pw.scrap_list_service'
        tags:
            -  { name: console.command }

    w.scrap.skill.site.page:
        class: AppBundle\Command\Core\RunTimeQueueCommand
        arguments:
            - 'w:scrap:skill:site:page'
            - '@pw.scrap_page_service'
        tags:
            -  { name: console.command }