services:
    conection_service:
        abstract:  true
        class: AppBundle\Service\ConnectionService
        arguments:
            - '@doctrine.dbal.default_connection'

    skill.structure_service:
        parent: conection_service
        class: AppBundle\Service\SkillSite\StructureService

    skill.analyze_structure_service:
        parent: conection_service
        class: AppBundle\Service\SkillSite\AnalyzeStructureService

    pd.profile.list.content.storage:
        class: AppBundle\Service\Scrap\ProfileListContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'skill_site_list_cache'

    pd.profile.content.storage:
        class: AppBundle\Service\Scrap\ProfileContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'skill_site_page_cache'

    pd.list.content.analyzer:
        class: AppBundle\Service\Scrap\ListContentAnalyzer
        arguments:
            - '/developers/'
            - '.next a'
            - '.profile'

    pw.list.content.analyzer:
        class: AppBundle\Service\Scrap\ListContentAnalyzer
        arguments:
            - '/resumes-it/'
            - '.perpageNavigation a'
            - '.tblSearch .ttl a.bf'

    pd.page_path_process:
        class: AppBundle\Service\Scrap\PagePathProcess
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'skill_site_page_queue'

    pd.scrap_list_service:
        class:  AppBundle\Service\Scrap\ListScraper
        arguments:
            - '@pd.profile.list.content.storage'
            - '@pd.list.content.analyzer'
            - '@pd.page_path_process'

    pd.scrap_page_service:
        class: AppBundle\Service\Scrap\PageScraper
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@pd.profile.content.storage'
            - '@pd.page_path_process'