services:
  conection_service:
    abstract:  true
    class: AppBundle\Service\ConnectionService
    arguments:
      - '@doctrine.dbal.default_connection'

  skill.structure_service:
    parent: conection_service
    class: AppBundle\Service\SkillSite\StructureService

  skill.analyze_structure_service:
    parent: conection_service
    class: AppBundle\Service\SkillSite\AnalyzeStructureService

  pd.profile.list.content.storage:
    parent: conection_service
    class: AppBundle\Service\Scrap\D\ProfileListContentStorage

  pd.profile.content.storage:
    parent: conection_service
    class: AppBundle\Service\Scrap\D\ProfileContentStorage

  pd.scrap_list_service:
    class:  AppBundle\Service\Scrap\D\ListScrapper
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@pd.profile.list.content.storage'

  pd.page_process:
    parent: conection_service
    class:  AppBundle\Service\Scrap\D\PageProcess

  pd.scrap_page_service:
    class: AppBundle\Service\Scrap\D\PageScraper
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@pd.profile.content.storage'
      - '@pd.page_process'