services:
    conection_service:
        abstract:  true
        class: AppBundle\Service\ConnectionService
        arguments:
            - '@doctrine.dbal.default_connection'

    skill.structure_service:
        parent: conection_service
        class: AppBundle\Service\SkillSite\StructureService

    skill.analyze_structure_service:
        parent: conection_service
        class: AppBundle\Service\SkillSite\AnalyzeStructureService

    pd.profile.list.content.storage:
        class: AppBundle\Service\Scrap\ProfileListContentStorage
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'skill_site_list_cache'

    pd.profile.content.storage:
        parent: conection_service
        class: AppBundle\Service\Scrap\D\ProfileContentStorage

    pd.list.content.analyzer:
        class: AppBundle\Service\Scrap\D\ListContentAnalyzer

    pd.page_path_queue:
        class: AppBundle\Service\Scrap\PagePathQueue
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'skill_site_page_queue'

    pd.scrap_list_service:
        class:  AppBundle\Service\Scrap\D\ListScrapper
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@pd.profile.list.content.storage'
            - '@pd.list.content.analyzer'
            - '@pd.page_path_queue'

    pd.page_process:
        parent: conection_service
        class:  AppBundle\Service\Scrap\D\PageProcess

    pd.scrap_page_service:
        class: AppBundle\Service\Scrap\D\PageScraper
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@pd.profile.content.storage'
            - '@pd.page_process'