parameters:
    pd.setting.uri: 'https://djinni.co/'
    pd.setting.pager_sequence_table: 'pd_sequence'
    pd.setting.profile_link_table: 'pd_profile_page_link'
    pd.setting.profile_table: 'pd_profile'
    pd.setting.pager_root_path: '/developers/'
    pd.setting.pager_selector_next: '.next a'
    pd.setting.profile_link_selector: '.profile'

services:
    pd.scrap.client:
        public: false
        class: 'GuzzleHttp\Client'
        arguments:
            - { base_uri: '%pd.setting.uri%' }

    pd.sequence.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\SequenceContentRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pd.setting.pager_sequence_table%'

    pd.profile.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\D\ProfileRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pd.setting.profile_table%'

    pd.sequence.pager:
        public: false
        class: 'ReenExe\Scrapynizer\Pager\PaginationHunter'
        arguments:
            - '%pd.setting.pager_root_path%'
            - '%pd.setting.pager_selector_next%'

    pd.sequence.link.collection.finder:
        public: false
        class: 'AppBundle\Service\Scrapynizer\LinkCollectionSelectorFinder'
        arguments:
            - '%pd.setting.profile_link_selector%'

    pd.path.process.repository:
        public: false
        class: 'AppBundle\Service\Scrapynizer\PathProcessRepository'
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%pd.setting.profile_link_table%'

    pd.link.collection.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\LinkCollectionAnalyzer'
        arguments:
            - '@pd.sequence.link.collection.finder'
            - '@pd.path.process.repository'

    pd.sequence.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\SequenceContentAnalyzer'
        arguments:
            - '@pd.link.collection.analyzer'

    pd.sequence.scraper:
        public: false
        class: 'ReenExe\Scrapynizer\Scraper\SequenceScraper'
        arguments:
            - '@pd.scrap.client'
            - '@pd.sequence.repository'
            - '@pd.sequence.pager'
            - '@pd.sequence.analyzer'

    pd.content.analyzer:
        public: false
        class: 'AppBundle\Service\Scrapynizer\D\ContentAnalyzer'
        arguments:
            - '@pd.profile.repository'

    pd.target.scrap:
        public: false
        class: 'ReenExe\Scrapynizer\Scraper\CollectionScraper'
        arguments:
            - '@pd.scrap.client'
            - '@pd.path.process.repository'
            - '@pd.content.analyzer'

    pd.sequence.scrap.command.adapter:
        public: false
        class: 'AppBundle\Service\Scrapynizer\QueueCommandAdapter'
        arguments:
            - '@pd.sequence.scraper'

    pd.scrap.target.command.adapter:
        public: false
        class: 'AppBundle\Service\Scrapynizer\QueueCommandAdapter'
        arguments:
            - '@pd.target.scrap'

    pd.sequence.scrap.target.list.command:
        class: 'AppBundle\Command\Core\RunTimeQueueCommand'
        arguments:
            - 'd:sequence:scrap:target:list'
            - '@pd.sequence.scrap.command.adapter'
        tags:
            -  { name: 'console.command' }

    pd.scrap.target.command:
        class: 'AppBundle\Command\Core\RunTimeQueueCommand'
        arguments:
            - 'd:scrap:target'
            - '@pd.scrap.target.command.adapter'
        tags:
            -  { name: 'console.command' }
